{% set name = "greykite" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/greykite-{{ version }}.tar.gz
  sha256: 14a163c04f3a81defb05b95d894a6565516c133f43b373aa999b630d17882bd0

build:
  entry_points:
    - greykite=greykite.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cvxpy >=1.2.1
    - dill >=0.3.1.1
    - holidays <0.25
    - holidays-ext >=0.0.7
    - ipython >=7.31.1
    - matplotlib-base >=3.4.1
    - numpy >=1.22.0,<1.25.0
    - osqp >=0.6.2
    - overrides >=2.8.0
    - pandas >=1.5.0,<2.0.0
    - patsy >=0.5.1
    - plotly >=4.12.0
    - pmdarima >=1.8.0,<=1.8.5
    - pytest >=4.6.5
    - pytest-runner >=5.1
    - scipy >=1.5.4,<1.11.0
    - six >=1.15.0
    - scikit-learn >=0.24.1
    - statsmodels >=0.12.2
    - testfixtures >=6.14.2
    - tqdm >=4.52.0

test:
  imports:
    - greykite
  commands:
    # cvxpy which is an indirect depdendency has bad deps
    # - pip check
    # cli is broken upstream
    # - greykite --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/linkedin/greykite
  summary: A python package for flexible forecasting
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
